services:
  postgres:
    image: postgres:16
    container_name: postgres-database
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: vibevault
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seeder/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - backend

  vibe-server:
    container_name: vibe-server
    image: registry.gitlab.com/frejem/vibevault/vibe-server:latest
    depends_on:
      - postgres
    env_file:
      - ./vibe-server/.env
    environment:
      RTE: ${RTE}
      JWT_SECRET: ${JWT_SECRET:-changeme}
      DATABASE_URL: postgresql://app1:changethispassword@postgres:5432/vibevault
    ports:
      - "5000:5000"
    networks:
      - backend
      - frontend
    volumes:
      - ./vibe-server/:/app

  vibe-client:
    container_name: vibe-client
    image: registry.gitlab.com/frejem/vibevault/vibe-client:latest
    environment:
      RTE: ${RTE}
      VITE_API_URL: http://localhost:8080/api/
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - postgres
    networks:
      - frontend
    volumes:
      - ./vibe-client:/app # mounted volume. For connecting our client folder to our docker app directory, and make it update when changes appear
      - /app/node_modules # exclude dependencies on the mount. If new depencies is added, we need to build again

  nginx:
    image: nginx:latest
    networks:
      - frontend
      - backend
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - 8080:80
    depends_on:
      - vibe-client
      - vibe-server

volumes:
  postgres_data:

networks:
  backend:
  frontend:
