services:
  postgres:
    image: postgres:16
    container_name: postgres-database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend

  # vibe-server:
  #   container_name: vibe-server
  #   build:
  #     context: ./vibe-server
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/mydatabase
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - backend
  #     - frontend
  #   volumes:
  #     - ./vibe-server/:/app

  vibe-client:
    container_name: vibe-client
    build:
      context: ./vibe-client
      dockerfile: Dockerfile
    environment:
      RTE: ${RTE}
      VITE_API_URL: http://localhost:5000
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - postgres
    networks:
      - frontend
    volumes:
      - ./vibe-client:/app # mounted volume. For connecting our client folder to our docker app directory, and make it update when changes appear
      - /app/node_modules # exclude dependencies on the mount. If new depencies is added, we need to build again

  nginx:
    image: nginx:latest
    networks:
      - frontend
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - 8080:80
    depends_on:
      - vibe-client
      # - vibe-server # add when server is added in docker compose

volumes:
  postgres_data:

networks:
  backend:
  frontend:
