name: CI Check on client

on:
  pull_request:
    branches:
      - main
    paths:
      - "vibe-client/**"
      - ".github/workflows/main_client.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Check if files in vibe-client have changed
        id: check_changed
        run: |
          git fetch --depth=1 origin main  # Ensure we are comparing against the latest main
          CHANGED_FILES=$(git diff --name-only HEAD..origin/main -- vibe-client/)
          if [[ -n "$CHANGED_FILES" ]]; then
            echo "vibe-client folder has changed"
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "No changes in vibe-client folder"
            echo "changed=false" >> $GITHUB_ENV
          fi
          echo "Changed files: $CHANGED_FILES"  # Debug: log changed files

      - name: npm install, build, and test
        if: env.changed == 'true'
        run: |
          cd vibe-client
          npm install
          npm run build --if-present
          npm run test --if-present
