name: CI Check on client

on:
  pull_request:
    branches:
      - main
    paths:
      - "vibe-client/**"
      - ".github/workflows/main_client.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Check if files in vibe-client have changed
        id: check_changed
        run: |
          git diff --exit-code vibe-client || echo "vibe-client folder has changed"

      - name: npm install, build, and test
        if: steps.check_changed.outputs.changed == 'true'
        run: |
          cd vibe-client
          npm install
          npm run build --if-present
          npm run test --if-present
